In [1]:
import pandas as pd

In [2]:
X_train=pd.read_csv(r'E:\\PayamPardaz\\NSL-KDD\\KDDTrain+_20Percent.txt')
#X_test=pd.read_csv(r'E:\\PayamPardaz\\NSL-KDD\\KDDTest+.txt')

In [3]:
X_train

,0,tcp,ftp_data,SF,491,0.1,0.2,0.3,0.4,0.5,...,0.17,0.03,0.17.1,0.00.6,0.00.7,0.00.8,0.05,0.00.9,normal,20
0,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.0,0.00,normal,15
1,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune,19
2,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.0,0.01,normal,21
3,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,normal,21
4,0,tcp,private,REJ,0,0,0,0,0,0,...,0.07,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25186,0,tcp,exec,RSTO,0,0,0,0,0,0,...,0.03,0.06,0.00,0.00,0.00,0.00,1.0,1.00,neptune,19
25187,0,tcp,ftp_data,SF,334,0,0,0,0,0,...,1.00,0.00,1.00,0.18,0.00,0.00,0.0,0.00,warezclient,12
25188,0,tcp,private,REJ,0,0,0,0,0,0,...,0.05,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune,21
25189,0,tcp,nnsp,S0,0,0,0,0,0,0,...,0.08,0.06,0.00,0.00,1.00,1.00,0.0,0.00,neptune,20
25190,0,tcp,finger,S0,0,0,0,0,0,0,...,0.19,0.03,0.01,0.00,1.00,1.00,0.0,0.00,neptune,18

In [4]:
def analyze_dataset(data):
    print('\nThe first rows are : ')
    print(data.head())
    print('\nThe data shape is : ')
    print(data.shape)
    print('\nThe data columns are : ')
    print(data.columns)
    
    print('\n\nThe data columns are : ')
    print(data.dtypes)
    columns = data.columns
    for col in columns:
        print('\n\nAll the unique values for {} are : '.format(col))
        print(data[col].unique())
        
    print('\n\nThe number of unique data columns are : ')
    print(data.nunique())
    print('\n\nThe number of none Null datas are : ')
    print(data.count())
    
    
    print('\n\nThe number of Null datas are : ')

    print(data.isnull().sum())
    print('\n\nThe Info : ')
    print(data.info())

In [5]:
#analyze_dataset(X_train)

In [6]:
X_train.head(2)

,0,tcp,ftp_data,SF,491,0.1,0.2,0.3,0.4,0.5,...,0.17,0.03,0.17.1,0.00.6,0.00.7,0.00.8,0.05,0.00.9,normal,20
0,0,udp,other,SF,146,0,0,0,0,0,...,0.0,0.60,0.88,0.0,0.0,0.0,0.0,0.0,normal,15
1,0,tcp,private,S0,0,0,0,0,0,0,...,0.1,0.05,0.00,0.0,1.0,1.0,0.0,0.0,neptune,19

In [7]:
len(X_train.columns)

43

In [8]:
X_train.columns

Index(['0', 'tcp', 'ftp_data', 'SF', '491', '0.1', '0.2', '0.3', '0.4', '0.5',
       '0.6', '0.7', '0.8', '0.9', '0.10', '0.11', '0.12', '0.13', '0.14',
       '0.15', '0.16', '0.18', '2', '2.1', '0.00', '0.00.1', '0.00.2',
       '0.00.3', '1.00', '0.00.4', '0.00.5', '150', '25', '0.17', '0.03',
       '0.17.1', '0.00.6', '0.00.7', '0.00.8', '0.05', '0.00.9', 'normal',
       '20'],
      dtype='object')

In [9]:
#X_test.columns

X_train.rename(columns={'0': 'duration' , 'tcp':'protocol_type'  , 'private':'service' , 'REJ':'flag', '491':'src_bytes' , '0.1':'dst_bytes' , '0.2':'land', '0.3':'wrong_fragment' , '0.4':'urgent' ,
                        '0.5':'hot',
       '0.6':'num_failed_logins' , '0.7':'logged_in' , '0.8':'num_compromised' , '0.9':'root_shell' , '0.10':'su_attempted' , '0.11':'num_root' , '0.12':'num_file_creations' , '0.13':'num_shells' , '0.14':'num_access_files' ,
       '0.15':'num_outbound_cmds' , '0.16':'is_host_login' , '0.18':'is_guest_login' , '2':'count', '2.1':'srv_count' , '0.00':'serror_rate' , '0.00.1':'srv_serror_rate' , '0.00.2':'rerror_rate' ,
       '0.00.3':'srv_rerror_rate' , '1.00':'same_srv_rate' , '0.00.4':'diff_srv_rate' , '0.00.5':'srv_diff_host_rate' , '150':'dst_host_count' 
                        , '25':'dst_host_srv_count' , '0.17':'dst_host_same_srv_rate' , '0.03':'dst_host_diff_srv_rate' ,
       '0.17.1':'dst_host_same_src_port_rate' , '0.00.6':'dst_host_srv_diff_host_rate' , '0.00.7':'dst_host_serror_rate' 
                        , '0.00.8':'dst_host_srv_serror_rate' , '0.05':'dst_host_rerror_rate' , '0.00.9':'dst_host_srv_rerror_rate' , 'normal':'class' ,
       },inplace=True)

In [10]:
X_train.rename(columns={'0': 'duration' , 'tcp':'protocol_type'  , 'ftp_data':'service' , 'SF':'flag', '491':'src_bytes' , '0.1':'dst_bytes' , '0.2':'land', '0.3':'wrong_fragment' , '0.4':'urgent' ,
                        '0.5':'hot',
       '0.6':'num_failed_logins' , '0.7':'logged_in' , '0.8':'num_compromised' , '0.9':'root_shell' , '0.10':'su_attempted' , '0.11':'num_root' , '0.12':'num_file_creations' , '0.13':'num_shells' , '0.14':'num_access_files' ,
       '0.15':'num_outbound_cmds' , '0.16':'is_host_login' , '0.18':'is_guest_login' , '2':'count', '2.1':'srv_count' , '0.00':'serror_rate' , '0.00.1':'srv_serror_rate' , '0.00.2':'rerror_rate' ,
       '0.00.3':'srv_rerror_rate' , '1.00':'same_srv_rate' , '0.00.4':'diff_srv_rate' , '0.00.5':'srv_diff_host_rate' , '150':'dst_host_count' 
                        , '25':'dst_host_srv_count' , '0.17':'dst_host_same_srv_rate' , '0.03':'dst_host_diff_srv_rate' ,
       '0.17.1':'dst_host_same_src_port_rate' , '0.00.6':'dst_host_srv_diff_host_rate' , '0.00.7':'dst_host_serror_rate' 
                        , '0.00.8':'dst_host_srv_serror_rate' , '0.05':'dst_host_rerror_rate' , '0.00.9':'dst_host_srv_rerror_rate' , 'normal':'class' ,
       },inplace=True)

In [11]:
X_train.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'class', '20'],
      dtype='object')

In [12]:
X_train['protocol_type'].nunique()

3

In [13]:
import pandas as pd

# Assuming you have a DataFrame called X_train with a column named 'protocol_type'
one_hot_encoded = pd.get_dummies(X_train['protocol_type'], prefix='protocol')
# Concatenate the one-hot encoded columns back to the original DataFrame
X_train = pd.concat([X_train, one_hot_encoded], axis=1)



# Assuming you have a DataFrame called X_train with a column named 'protocol_type'
#one_hot_encoded = pd.get_dummies(X_test['protocol_type'], prefix='protocol')
# Concatenate the one-hot encoded columns back to the original DataFrame
#X_test = pd.concat([X_test, one_hot_encoded], axis=1)

In [14]:
#X_train.drop('protocol_type_encoded',axis=1)

#X_test.drop('protocol_type_encoded',axis=1)

In [15]:
X_train.drop('protocol_type',axis=1)
#X_test.drop('protocol_type',axis=1)

,duration,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class,20,protocol_icmp,protocol_tcp,protocol_udp
0,0,other,SF,146,0,0,0,0,0,0,...,0.00,0.00,0.00,0.0,0.00,normal,15,0,0,1
1,0,private,S0,0,0,0,0,0,0,0,...,0.00,1.00,1.00,0.0,0.00,neptune,19,0,1,0
2,0,http,SF,232,8153,0,0,0,0,0,...,0.04,0.03,0.01,0.0,0.01,normal,21,0,1,0
3,0,http,SF,199,420,0,0,0,0,0,...,0.00,0.00,0.00,0.0,0.00,normal,21,0,1,0
4,0,private,REJ,0,0,0,0,0,0,0,...,0.00,0.00,0.00,1.0,1.00,neptune,21,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25186,0,exec,RSTO,0,0,0,0,0,0,0,...,0.00,0.00,0.00,1.0,1.00,neptune,19,0,1,0
25187,0,ftp_data,SF,334,0,0,0,0,0,0,...,0.18,0.00,0.00,0.0,0.00,warezclient,12,0,1,0
25188,0,private,REJ,0,0,0,0,0,0,0,...,0.00,0.00,0.00,1.0,1.00,neptune,21,0,1,0
25189,0,nnsp,S0,0,0,0,0,0,0,0,...,0.00,1.00,1.00,0.0,0.00,neptune,20,0,1,0
25190,0,finger,S0,0,0,0,0,0,0,0,...,0.00,1.00,1.00,0.0,0.00,neptune,18,0,1,0

In [16]:
one_hot_encoded = pd.get_dummies(X_train['service'], prefix='service')
X_train = pd.concat([X_train, one_hot_encoded], axis=1)



#one_hot_encoded = pd.get_dummies(X_test['service'], prefix='service')
#X_test = pd.concat([X_test, one_hot_encoded], axis=1)

In [17]:
X_train.drop('service',axis=1)
#X_test.drop('service',axis=1)

,duration,protocol_type,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,service_systat,service_telnet,service_tim_i,service_time,service_urh_i,service_urp_i,service_uucp,service_uucp_path,service_vmnet,service_whois
0,0,udp,SF,146,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,tcp,S0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,tcp,SF,232,8153,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,tcp,SF,199,420,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,tcp,REJ,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25186,0,tcp,RSTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25187,0,tcp,SF,334,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25188,0,tcp,REJ,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25189,0,tcp,S0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25190,0,tcp,S0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
X_train = X_train.drop(['service','protocol_type'],axis=1)
#X_test = X_test.drop(['service','protocol_type'],axis=1)

In [19]:
X_train

,duration,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,...,service_systat,service_telnet,service_tim_i,service_time,service_urh_i,service_urp_i,service_uucp,service_uucp_path,service_vmnet,service_whois
0,0,SF,146,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,S0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,SF,232,8153,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0,SF,199,420,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,REJ,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25186,0,RSTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25187,0,SF,334,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25188,0,REJ,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25189,0,S0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25190,0,S0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
one_hot_encoded = pd.get_dummies(X_train['flag'], prefix='protocol')
X_train = pd.concat([X_train, one_hot_encoded], axis=1)


#one_hot_encoded = pd.get_dummies(X_test['flag'], prefix='protocol')
#X_test = pd.concat([X_test, one_hot_encoded], axis=1)

In [21]:
X_train = X_train.drop(['flag'],axis=1)
#X_test = X_test.drop(['flag'],axis=1)

In [22]:
X_train

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,protocol_REJ,protocol_RSTO,protocol_RSTOS0,protocol_RSTR,protocol_S0,protocol_S1,protocol_S2,protocol_S3,protocol_SF,protocol_SH
0,0,146,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,232,8153,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,0,199,420,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25186,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25187,0,334,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
25188,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25189,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25190,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [23]:
#V=X_train.copy()

In [24]:
#X_trn = V.drop(['class'], axis=1)
#y_trn = V['class']

In [25]:
X_train.isnull().sum()

duration          0
src_bytes         0
dst_bytes         0
land              0
wrong_fragment    0
                 ..
protocol_S1       0
protocol_S2       0
protocol_S3       0
protocol_SF       0
protocol_SH       0
Length: 120, dtype: int64

In [26]:
duplicates = X_train[X_train.duplicated()]
duplicates

Empty DataFrame
Columns: [duration, src_bytes, dst_bytes, land, wrong_fragment, urgent, hot, num_failed_logins, logged_in, num_compromised, root_shell, su_attempted, num_root, num_file_creations, num_shells, num_access_files, num_outbound_cmds, is_host_login, is_guest_login, count, srv_count, serror_rate, srv_serror_rate, rerror_rate, srv_rerror_rate, same_srv_rate, diff_srv_rate, srv_diff_host_rate, dst_host_count, dst_host_srv_count, dst_host_same_srv_rate, dst_host_diff_srv_rate, dst_host_same_src_port_rate, dst_host_srv_diff_host_rate, dst_host_serror_rate, dst_host_srv_serror_rate, dst_host_rerror_rate, dst_host_srv_rerror_rate, class, 20, protocol_icmp, protocol_tcp, protocol_udp, service_IRC, service_X11, service_Z39_50, service_auth, service_bgp, service_courier, service_csnet_ns, service_ctf, service_daytime, service_discard, service_domain, service_domain_u, service_echo, service_eco_i, service_ecr_i, service_efs, service_exec, service_finger, service_ftp, service_ftp_data, service_gopher, service_hostnames, service_http, service_http_443, service_http_8001, service_imap4, service_iso_tsap, service_klogin, service_kshell, service_ldap, service_link, service_login, service_mtp, service_name, service_netbios_dgm, service_netbios_ns, service_netbios_ssn, service_netstat, service_nnsp, service_nntp, service_ntp_u, service_other, service_pm_dump, service_pop_2, service_pop_3, service_printer, service_private, service_red_i, service_remote_job, service_rje, service_shell, service_smtp, service_sql_net, service_ssh, service_sunrpc, service_supdup, service_systat, ...]
Index: []

[0 rows x 120 columns]

In [27]:
import numpy as np
# Calculate the z-scores for each data point
X=X_train
z_scores = np.abs((X - np.mean(X)) / np.std(X))

# Define a threshold for identifying outliers (e.g., z-score greater than 3)
threshold = 3

# Create a Boolean mask to identify outlier indices
outlier_mask = z_scores > threshold

# Delete rows corresponding to outliers
data_without_outliers = X[~outlier_mask]

# Print the dataset without outliers
print(data_without_outliers)

C:\Users\BiG\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
C:\Users\BiG\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
C:\Users\BiG\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3571: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

       duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0           0.0      146.0        0.0   0.0             0.0     0.0  0.0
1           0.0        0.0        0.0   0.0             0.0     0.0  0.0
2           0.0      232.0     8153.0   0.0             0.0     0.0  0.0
3           0.0      199.0      420.0   0.0             0.0     0.0  0.0
4           0.0        0.0        0.0   0.0             0.0     0.0  0.0
...         ...        ...        ...   ...             ...     ...  ...
25186       0.0        0.0        0.0   0.0             0.0     0.0  0.0
25187       0.0      334.0        0.0   0.0             0.0     0.0  0.0
25188       0.0        0.0        0.0   0.0             0.0     0.0  0.0
25189       0.0        0.0        0.0   0.0             0.0     0.0  0.0
25190       0.0        0.0        0.0   0.0             0.0     0.0  0.0

       num_failed_logins  logged_in  num_compromised  ...  protocol_REJ  \
0                    0.0          0              0.0  ...           0.0
1                    0.0          0              0.0  ...           0.0
2                    0.0          1              0.0  ...           0.0
3                    0.0          1              0.0  ...           0.0
4                    0.0          0              0.0  ...           NaN
...                  ...        ...              ...  ...           ...
25186                0.0          0              0.0  ...           0.0
25187                0.0          1              0.0  ...           0.0
25188                0.0          0              0.0  ...           NaN
25189                0.0          0              0.0  ...           0.0
25190                0.0          0              0.0  ...           0.0

       protocol_RSTO  protocol_RSTOS0  protocol_RSTR  protocol_S0  \
0                0.0              0.0            0.0            0
1                0.0              0.0            0.0            1
2                0.0              0.0            0.0            0
3                0.0              0.0            0.0            0
4                0.0              0.0            0.0            0
...              ...              ...            ...          ...
25186            NaN              0.0            0.0            0
25187            0.0              0.0            0.0            0
25188            0.0              0.0            0.0            0
25189            0.0              0.0            0.0            1
25190            0.0              0.0            0.0            1

       protocol_S1  protocol_S2  protocol_S3  protocol_SF  protocol_SH
0              0.0          0.0          0.0            1          0.0
1              0.0          0.0          0.0            0          0.0
2              0.0          0.0          0.0            1          0.0
3              0.0          0.0          0.0            1          0.0
4              0.0          0.0          0.0            0          0.0
...            ...          ...          ...          ...          ...
25186          0.0          0.0          0.0            0          0.0
25187          0.0          0.0          0.0            1          0.0
25188          0.0          0.0          0.0            0          0.0
25189          0.0          0.0          0.0            0          0.0
25190          0.0          0.0          0.0            0          0.0

[25191 rows x 120 columns]

In [28]:
X_train.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,protocol_REJ,protocol_RSTO,protocol_RSTOS0,protocol_RSTR,protocol_S0,protocol_S1,protocol_S2,protocol_S3,protocol_SF,protocol_SH
0,0,146,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,232,8153,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,0,199,420,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

## lets get to train a machine learning model

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

X_trn = X_train.drop(['class'], axis=1)
y_trn = X_train['class']

cols_train=X_trn.columns
pca = PCA(n_components=5)
X_train = X_train[cols_train].to_numpy()
X_train = pca.fit_transform(X_train)
X_train.shape[1]


X_train, X_test, y_train, y_test = train_test_split(X_trn, y_trn, test_size=0.2, random_state=42)

In [30]:
from sklearn.preprocessing import MinMaxScaler

# Assuming you have a DataFrame called df with multiple columns to normalize
columns_to_normalize = X_trn.columns
scaler = MinMaxScaler()  # Create MinMaxScaler object

X_train[columns_to_normalize] = scaler.fit_transform(X_train[columns_to_normalize])  # Apply normalization to selected columns

# Print the normalized DataFrame
X_train

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,protocol_REJ,protocol_RSTO,protocol_RSTOS0,protocol_RSTR,protocol_S0,protocol_S1,protocol_S2,protocol_S3,protocol_SF,protocol_SH
2199,0.000000,9.483662e-07,0.000047,0.0,0.0,0.0,0.000000,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
15287,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4139,0.000000,5.318186e-07,0.010913,0.0,0.0,0.0,0.000000,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3505,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
24159,0.000000,1.100314e-07,0.000023,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21575,0.019644,2.774364e-06,0.000598,0.0,0.0,0.0,0.285714,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5390,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
860,0.000000,8.933505e-07,0.000055,0.0,0.0,0.0,0.000000,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
15795,0.000000,1.205106e-07,0.000022,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
23654,0.000000,8.645327e-08,0.000006,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score


# Create a DecisionTreeClassifier
clf = DecisionTreeClassifier()

# Train the classifier
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9188331018059138

In [32]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5512998610835483

In [33]:
from sklearn.neighbors import KNeighborsClassifier

# Create a KNeighborsClassifier
clf = KNeighborsClassifier()

# Train the classifier
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.1412978765628101

In [34]:
from sklearn.svm import SVC
# Create a SVC classifier
clf = SVC()

# Train the classifier
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.540583449097043

In [35]:
from sklearn.neural_network import MLPClassifier

# Create an MLPClassifier
clf = MLPClassifier()

# Train the classifier
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.05755110140900972

## as result we can see that DecisionTreeClassifier was the best one!